/* ============================================================================
 * SparkFlow File Header
 * File: SparkFlow.Abstractions/Services/Health/Abstractions/IHealthCheckProvider.cs
 * Purpose: Core component: IHealthCheckProvider.
 * Notes:
 *  - This file is part of the SparkFlow automation platform.
 *  - Comments are intentionally kept in English for consistency across the codebase.
 * ============================================================================ */

using SparkFlow.Abstractions.Models;

namespace SparkFlow.Abstractions.Services.Health.Abstractions;

/// <summary>
/// A single health provider. Each provider contributes issues and may implement auto-fix.
/// </summary>
public interface IHealthCheckProvider
{
    string Name { get; }

    /// <summary>
    /// Run health checks for the given profile.
    /// </summary>
    Task<IReadOnlyList<HealthIssue>> CheckAsync(string profileId, CancellationToken ct = default);

    /// <summary>
    /// Try to apply auto fixes for issues generated by this provider.
    /// Must NOT perform game actions. Environment-only fixes.
    /// </summary>
    Task<int> FixAllAutoAsync(string profileId, CancellationToken ct = default);
}